### PR TITLE
Added email functionality

### PR DESCRIPTION
**Pull request by Theskyspace**
Now user can receive his/her certificate on emails

- [x]  Moved the project to flask for scalability and smooth integration.
- [x] Used smtplib to sent the emails.
- [x] Added a Responsive user interface to the functionality
- [x] Added requirement txt

### CODE REVIEW

**Comment by Theskyspace** [comment]
This PR was made as a part of the participation from hacktoberfest, So if you find it useful you can help me out by making this pr count by the following rules :
A pull request is considered approved once it has an overall approving review from maintainers, or has been merged by maintainers, or has been given the 'hacktoberfest-accepted' label.

Thanks, 
It was a fun project

**Comment by Theskyspace** [comment]
It was checked, and it is working all you need to do just fill in the credentials for a Gmail account

**Comment by akshitadixit** [comment]
@Ayush0922 kindly merge this under the required labels

**Comment by mohit355** [comment]
Will merge it after review by EOD today

**Comment by Ayush0922** [comment]
> @Ayush0922 kindly merge this under the required labels

yeah still under review..will merge today if passes the needs

**Review by Ayush0922 — APPROVED** [review]
looks good and works ok.

**Pull request merged**
